version: 2.1
# orbs:
#   heroku: circleci/heroku@0.0.10

jobs:
  build:
    docker:
      - image: cimg/node:17.3.0
    steps:
      - checkout
      - run: echo "Hello World"
  mac-runner:
      machine: true
      resource_class:  myorg-namespace/mac-runner
      steps:
        - run: echo "Hello Runner"
#   heroku/deploy-via-git:
#     circleci_ip_ranges: true
#     docker:
#       - image: cimg/node:17.3.0
#     steps:
#       - checkout
#       - run: node --version
# parameters:
#   run-schedule:
#     type: boolean
#     default: false
workflows:
  build_and_deploy:
    jobs:
      - build
      - mac-runner
