version: 2.1
orbs:
  heroku: circleci/heroku@0.0.10

jobs:
  build:
    circleci_ip_ranges: true
    docker:
      - image: cimg/node:17.3.0
    steps:
      - checkout
      - run: echo "Hello World"
  heroku/deploy-via-git:
    circleci_ip_ranges: true
    docker:
      - image: cimg/node:17.3.0
    steps:
      - checkout
      - run: node --version
parameters:
  run-schedule:
    type: boolean
    default: false
workflows:
  build_and_deploy:
    when: << pipeline.parameters.run-schedule >>
    # when:
    #   and:
    #     - equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
    #     - equal: [ "test-schedule", << pipeline.schedule.name >> ]
    jobs:
      - build
      - heroku/deploy-via-git
