version: 2.1
orbs:
  heroku: circleci/heroku@0.0.10
# workflows:
#   heroku_deploy:
#     jobs:
#     - heroku/deploy-via-git

jobs:
  build:
    circleci_ip_ranges: true
    docker:
      - image: cimg/node:17.3.0
    steps:
      - checkout
      - run: echo "Hello World"
  heroku/deploy-via-git:
    docker:
      - image: cimg/node:17.3.0
    steps:
      - checkout
      - run: node --version
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - heroku/deploy-via-git