version: 2.1
# orbs:
#   heroku: circleci/heroku@0.0.10

jobs:
  build:
    docker:
      - image: cimg/node:17.3.0
    steps:
      - checkout
      - run: echo "Hello World"
  runner-test-one:
    machine: true
    resource_class: myorg-namespace/mac-runner
    steps:
      - run: echo "Hi I'm on Runners!"
  runner-test-two:
    machine: true
    resource_class: myorg-namespace/macrunner-test
    steps:
      - run: echo "Hi I'm on Runners!"
workflows:
  build_and_deploy:
    jobs:
      - build
      - runner-test-one
      - runner-test-two

